/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package card.model.impl;

import aQute.bnd.annotation.ProviderType;

import card.model.Drink;
import card.model.DrinkModel;
import card.model.DrinkSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Drink service. Represents a row in the &quot;MenuCard_Drink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DrinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DrinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DrinkImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DrinkModelImpl extends BaseModelImpl<Drink> implements DrinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a drink model instance should use the <code>Drink</code> interface instead.
	 */
	public static final String TABLE_NAME = "MenuCard_Drink";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"drinkId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"price", Types.INTEGER},
		{"description", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("drinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("price", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MenuCard_Drink (uuid_ VARCHAR(75) null,drinkId LONG not null primary key,name VARCHAR(75) null,price INTEGER,description VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table MenuCard_Drink";

	public static final String ORDER_BY_JPQL = " ORDER BY drink.drinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MenuCard_Drink.drinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		card.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.card.model.Drink"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		card.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.card.model.Drink"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		card.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.card.model.Drink"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long PRICE_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long DRINKID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Drink toModel(DrinkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Drink model = new DrinkImpl();

		model.setUuid(soapModel.getUuid());
		model.setDrinkId(soapModel.getDrinkId());
		model.setName(soapModel.getName());
		model.setPrice(soapModel.getPrice());
		model.setDescription(soapModel.getDescription());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Drink> toModels(DrinkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Drink> models = new ArrayList<Drink>(soapModels.length);

		for (DrinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		card.service.util.ServiceProps.get(
			"lock.expiration.time.card.model.Drink"));

	public DrinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _drinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDrinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _drinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Drink.class;
	}

	@Override
	public String getModelClassName() {
		return Drink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Drink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Drink, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Drink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Drink, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Drink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Drink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Drink, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Drink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Drink>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Drink.class.getClassLoader(), Drink.class, ModelWrapper.class);

		try {
			Constructor<Drink> constructor =
				(Constructor<Drink>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Drink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Drink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Drink, Object>>();
		Map<String, BiConsumer<Drink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Drink, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object uuid) {
					drink.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"drinkId",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getDrinkId();
				}

			});
		attributeSetterBiConsumers.put(
			"drinkId",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object drinkId) {
					drink.setDrinkId((Long)drinkId);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object name) {
					drink.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"price",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getPrice();
				}

			});
		attributeSetterBiConsumers.put(
			"price",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object price) {
					drink.setPrice((Integer)price);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object description) {
					drink.setDescription((String)description);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object groupId) {
					drink.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object companyId) {
					drink.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object userId) {
					drink.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object userName) {
					drink.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object createDate) {
					drink.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Drink, Object>() {

				@Override
				public Object apply(Drink drink) {
					return drink.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Drink, Object>() {

				@Override
				public void accept(Drink drink, Object modifiedDate) {
					drink.setModifiedDate((Date)modifiedDate);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDrinkId() {
		return _drinkId;
	}

	@Override
	public void setDrinkId(long drinkId) {
		_columnBitmask = -1L;

		_drinkId = drinkId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public int getPrice() {
		return _price;
	}

	@Override
	public void setPrice(int price) {
		_columnBitmask |= PRICE_COLUMN_BITMASK;

		if (!_setOriginalPrice) {
			_setOriginalPrice = true;

			_originalPrice = _price;
		}

		_price = price;
	}

	public int getOriginalPrice() {
		return _originalPrice;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Drink.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Drink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Drink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Drink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DrinkImpl drinkImpl = new DrinkImpl();

		drinkImpl.setUuid(getUuid());
		drinkImpl.setDrinkId(getDrinkId());
		drinkImpl.setName(getName());
		drinkImpl.setPrice(getPrice());
		drinkImpl.setDescription(getDescription());
		drinkImpl.setGroupId(getGroupId());
		drinkImpl.setCompanyId(getCompanyId());
		drinkImpl.setUserId(getUserId());
		drinkImpl.setUserName(getUserName());
		drinkImpl.setCreateDate(getCreateDate());
		drinkImpl.setModifiedDate(getModifiedDate());

		drinkImpl.resetOriginalValues();

		return drinkImpl;
	}

	@Override
	public int compareTo(Drink drink) {
		int value = 0;

		if (getDrinkId() < drink.getDrinkId()) {
			value = -1;
		}
		else if (getDrinkId() > drink.getDrinkId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Drink)) {
			return false;
		}

		Drink drink = (Drink)obj;

		long primaryKey = drink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DrinkModelImpl drinkModelImpl = this;

		drinkModelImpl._originalUuid = drinkModelImpl._uuid;

		drinkModelImpl._originalName = drinkModelImpl._name;

		drinkModelImpl._originalPrice = drinkModelImpl._price;

		drinkModelImpl._setOriginalPrice = false;

		drinkModelImpl._originalGroupId = drinkModelImpl._groupId;

		drinkModelImpl._setOriginalGroupId = false;

		drinkModelImpl._originalCompanyId = drinkModelImpl._companyId;

		drinkModelImpl._setOriginalCompanyId = false;

		drinkModelImpl._setModifiedDate = false;

		drinkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Drink> toCacheModel() {
		DrinkCacheModel drinkCacheModel = new DrinkCacheModel();

		drinkCacheModel.uuid = getUuid();

		String uuid = drinkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			drinkCacheModel.uuid = null;
		}

		drinkCacheModel.drinkId = getDrinkId();

		drinkCacheModel.name = getName();

		String name = drinkCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			drinkCacheModel.name = null;
		}

		drinkCacheModel.price = getPrice();

		drinkCacheModel.description = getDescription();

		String description = drinkCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			drinkCacheModel.description = null;
		}

		drinkCacheModel.groupId = getGroupId();

		drinkCacheModel.companyId = getCompanyId();

		drinkCacheModel.userId = getUserId();

		drinkCacheModel.userName = getUserName();

		String userName = drinkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			drinkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			drinkCacheModel.createDate = createDate.getTime();
		}
		else {
			drinkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			drinkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			drinkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return drinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Drink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Drink, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Drink)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Drink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Drink, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Drink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Drink>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _drinkId;
	private String _name;
	private String _originalName;
	private int _price;
	private int _originalPrice;
	private boolean _setOriginalPrice;
	private String _description;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private Drink _escapedModel;

}