/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package menu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Drink service. Represents a row in the &quot;Menu_Drink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>menu.model.impl.DrinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>menu.model.impl.DrinkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Drink
 * @generated
 */
@ProviderType
public interface DrinkModel extends BaseModel<Drink> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a drink model instance should use the {@link Drink} interface instead.
	 */

	/**
	 * Returns the primary key of this drink.
	 *
	 * @return the primary key of this drink
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this drink.
	 *
	 * @param primaryKey the primary key of this drink
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this drink.
	 *
	 * @return the uuid of this drink
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this drink.
	 *
	 * @param uuid the uuid of this drink
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the drink ID of this drink.
	 *
	 * @return the drink ID of this drink
	 */
	public long getDrinkId();

	/**
	 * Sets the drink ID of this drink.
	 *
	 * @param drinkId the drink ID of this drink
	 */
	public void setDrinkId(long drinkId);

	/**
	 * Returns the name of this drink.
	 *
	 * @return the name of this drink
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this drink.
	 *
	 * @param name the name of this drink
	 */
	public void setName(String name);

	/**
	 * Returns the price of this drink.
	 *
	 * @return the price of this drink
	 */
	public int getPrice();

	/**
	 * Sets the price of this drink.
	 *
	 * @param price the price of this drink
	 */
	public void setPrice(int price);

	/**
	 * Returns the create date of this drink.
	 *
	 * @return the create date of this drink
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this drink.
	 *
	 * @param createDate the create date of this drink
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this drink.
	 *
	 * @return the modified date of this drink
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this drink.
	 *
	 * @param modifiedDate the modified date of this drink
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(menu.model.Drink drink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<menu.model.Drink> toCacheModel();

	@Override
	public menu.model.Drink toEscapedModel();

	@Override
	public menu.model.Drink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}