/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package menu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Food service. Represents a row in the &quot;Menu_Food&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>menu.model.impl.FoodModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>menu.model.impl.FoodImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Food
 * @generated
 */
@ProviderType
public interface FoodModel extends BaseModel<Food> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a food model instance should use the {@link Food} interface instead.
	 */

	/**
	 * Returns the primary key of this food.
	 *
	 * @return the primary key of this food
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this food.
	 *
	 * @param primaryKey the primary key of this food
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this food.
	 *
	 * @return the uuid of this food
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this food.
	 *
	 * @param uuid the uuid of this food
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the food ID of this food.
	 *
	 * @return the food ID of this food
	 */
	public long getFoodId();

	/**
	 * Sets the food ID of this food.
	 *
	 * @param foodId the food ID of this food
	 */
	public void setFoodId(long foodId);

	/**
	 * Returns the name of this food.
	 *
	 * @return the name of this food
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this food.
	 *
	 * @param name the name of this food
	 */
	public void setName(String name);

	/**
	 * Returns the details of this food.
	 *
	 * @return the details of this food
	 */
	@AutoEscape
	public String getDetails();

	/**
	 * Sets the details of this food.
	 *
	 * @param details the details of this food
	 */
	public void setDetails(String details);

	/**
	 * Returns the spicy of this food.
	 *
	 * @return the spicy of this food
	 */
	public boolean getSpicy();

	/**
	 * Returns <code>true</code> if this food is spicy.
	 *
	 * @return <code>true</code> if this food is spicy; <code>false</code> otherwise
	 */
	public boolean isSpicy();

	/**
	 * Sets whether this food is spicy.
	 *
	 * @param spicy the spicy of this food
	 */
	public void setSpicy(boolean spicy);

	/**
	 * Returns the price of this food.
	 *
	 * @return the price of this food
	 */
	public int getPrice();

	/**
	 * Sets the price of this food.
	 *
	 * @param price the price of this food
	 */
	public void setPrice(int price);

	/**
	 * Returns the create date of this food.
	 *
	 * @return the create date of this food
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this food.
	 *
	 * @param createDate the create date of this food
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this food.
	 *
	 * @return the modified date of this food
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this food.
	 *
	 * @param modifiedDate the modified date of this food
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(menu.model.Food food);

	@Override
	public int hashCode();

	@Override
	public CacheModel<menu.model.Food> toCacheModel();

	@Override
	public menu.model.Food toEscapedModel();

	@Override
	public menu.model.Food toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}